### ISSUE TITLE
Choose better password storage

### ISSUE THREAD

**Issue by beuiot** [nestorInc/jukebox#86]
check the law

**Comment by TiTi** [comment]
![](http://i2.kym-cdn.com/photos/images/original/000/479/591/e6a.jpg)


Bon alors je pense avoir retrouvé l'origine de l'intuition d'Olivier : la loi LCEN.
http://www.numerama.com/magazine/18207-decret-lcen-la-cnil-ignore-la-conservation-des-mots-de-passe.html

Mais en regardant plus attentivement : 
https://blog.crimenumerique.fr/2011/03/04/decret-dapplication-de-la-lcen-sur-la-conservation-des-donnees-par-les-fai-et-hebergeurs/

> Le mot de passe (si le système utilisé stocke le mot de passe en clair) ainsi que les données permettant de le vérifier (hashs ou autres techniques permettant de stocker de façon sécurisée un mot de passe) ou de le modifier, dans leur dernière version mise à jour ;

Ca semble moins clair sur legifrance: https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000023646013&categorieLien=id
ah par là en fait : https://www.legifrance.gouv.fr/affichTexte.do;jsessionid=?cidTexte=JORFTEXT000023646852&dateTexte=&oldAction=rechJO&categorieLien=id

Cet article explique bien :
https://www.hleroy.com/post/2011/03/10/La-LCEN-a-enfin-son-d%C3%A9cret-d-application...-et-d%C3%A9j%C3%A0-critiqu%C3%A9


Un peu beaucoup flippant le décallage avec la réalité >.<

Cela dit tous les bons tutos. sur le sujet expliquent l'importance d'utiliser une "one-way (irreversible) function". Ex: https://www.owasp.org/index.php/Password_Storage_Cheat_Sheet

Et je n'ai pas souvenir d'avoir entendu de grand changements sur le sujet pour tous les systèmes en places (penser sites connus).

----

http://www.ssi.gouv.fr/administration/reglementation/controle-reglementaire-sur-la-cryptographie/

http://blog.developpez.com/sqlpro/p12496/langage-sql-norme/hachage-nest-pas-cryptage-de-la-securite-des-donnees-chiffrees-dans-les-sgbdr

**Comment by TiTi** [comment]
Apparemment Google, Facebook et EBay avaient rapidemment déposés des plaintes :
http://www.presse-citron.net/google-facebook-et-ebay-deposent-une-plainte-contre-la-loi-francaise-de-conservation-des-donnees-des-utilisateurs/

Faudrait voir si on peut les retrouver et préciser comment elles ont abouties / ou elles en sont.

**Comment by lilianm** [comment]
De souvenir il y a une obligation de garder les identifiants et données sensibles de facon sure si on considere du cote de la CNIL. Perso je pense que le hachage des mots de passe est tolere

**Comment by beuiot** [comment]
Punaise je savait pas que la LCEN avait passé le décret d'application..
Cette loi est affolante. Je serais curieux de savoir dans quelle mesure c'est appliqué dans la 'vraie' vie des éditeurs de services / hébergeurs.

Je vote pour qu'on fasse ce qui est bien niveau sécurité: fonction irréversible. Vous en pensez quoi ?

**Comment by TiTi** [comment]
hash sha2 ou alike + salt
la prochaine étape ca sera éviter les brutes forces
puis celle d'après les timings attack
maias bon là ca devient plus un coffre fort qu'un jukebox :-p

**Comment by beuiot** [comment]
ben on est bons alors : https://github.com/nestorInc/jukebox/pull/85/files#diff-dabe571773c8d4ff1d73db163b02865fR139

`salt_pass = Digest::SHA256.base64digest(salt + pass);`

Pour les timings et les brute force, je pense que ça relève plus de la configuration d'apache (vu qu'il est en frontal !)

**Comment by lilianm** [comment]
Deja fait en effet
